import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar/Navbar";
import { StateContextProvider } from "./context/StateContext";
import AuthProvider from "./auth/Provider";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <StateContextProvider>
            <Toaster />
            <Navbar />
            <main className="mx-auto px-6 md:px-6 max-sm:px-2 lg:max-w-6xl">
              {children}
            </main>
            <Footer />
          </StateContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
