import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar/Navbar";
import { StateContextProvider } from "./context/StateContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContextProvider>
          <Toaster />
          <Navbar />
          <div className="mx-auto max-w-2xl sm:px-6 lg:max-w-6xl">
            {children}
          </div>
        </StateContextProvider>
      </body>
    </html>
  );
}
